#ifndef CPPBASE_CONFIG_HPP
#define CPPBASE_CONFIG_HPP

#if __cplusplus < 201703L
#error "cppbase requires C++17 or higher compiler standard!"
#endif

#define CPPBASE_OS_UNKNOWN 0
#define CPPBASE_OS_WINDOWS 1
#define CPPBASE_OS_LINUX   2
#define CPPBASE_OS_MACOS   3

#define CPPBASE_COMPILER_UNKNOWN 0
#define CPPBASE_COMPILER_MSVC    1
#define CPPBASE_COMPILER_GCC     2
#define CPPBASE_COMPILER_CLANG   3

#ifdef _WIN32
#   define CPPBASE_OS CPPBASE_OS_WINDOWS
#elif __linux__
#   define CPPBASE_OS CPPBASE_OS_LINUX
#elif __APPLE__
#   define CPPBASE_OS CPPBASE_OS_MACOS
#else
#   define CPPBASE_OS CPPBASE_OS_UNKNOWN
#endif

#ifdef _MSC_VER
#   define CPPBASE_COMPILER CPPBASE_COMPILER_MSVC
#elif __GNUC__
#   define CPPBASE_COMPILER CPPBASE_COMPILER_GCC
#elif __clang__
#   define CPPBASE_COMPILER CPPBASE_COMPILER_CLANG
#else
#   define CPPBASE_COMPILER CPPBASE_COMPILER_UNKNOWN
#endif

#define CPPBASE_IS_WINDOWS     (CPPBASE_OS == CPPBASE_OS_WINDOWS)
#define CPPBASE_IS_LINUX       (CPPBASE_OS == CPPBASE_OS_LINUX)
#define CPPBASE_IS_MACOS       (CPPBASE_OS == CPPBASE_OS_MACOS)

#define CPPBASE_IS_MSVC     (CPPBASE_COMPILER == CPPBASE_COMPILER_MSVC)
#define CPPBASE_IS_GCC      (CPPBASE_COMPILER == CPPBASE_COMPILER_GCC)
#define CPPBASE_IS_CLANG    (CPPBASE_COMPILER == CPPBASE_COMPILER_CLANG)
#define CPPBASE_IS_GNU      (CPPBASE_IS_GCC || CPPBASE_IS_CLANG) 

#define CPPBASE_DISABLE_COPY(CLASS_NAME) \
    CLASS_NAME(const CLASS_NAME&) = delete; \
    CLASS_NAME& operator=(const CLASS_NAME&) = delete;

#define CPPBASE_DISABLE_MOVE(CLASS_NAME) \
    CLASS_NAME(CLASS_NAME&&) = delete; \
    CLASS_NAME& operator=(CLASS_NAME&&) = delete;

#endif // CPPBASE_CONFIG_HPP